server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

plugins:
  youtube:
    enabled: true
  spotify:
    clientId: ""
    clientSecret: ""
    enabled: true
  soundcloud:
    enabled: true
