server:
  port: 443

lavalink:
  server:
    password: "free"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    gc-warnings: true
