version: "3.9"

services:
  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=maxverstappentututu

  bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    depends_on:
      - lavalink
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "bot.py"]
